### PR TITLE
Fix for issue 84

### PR DESCRIPTION
**Pull request by aovestdipaperino**
https://github.com/T-vK/ESP32-BLE-Keyboard/issues/84
Tested on iOS, Windows, Mac
Please generate a release after merging. 👍🏻

### CODE REVIEW

**Comment by T-vK** [comment]
I tested it on Linux and Android. It's merged now and I've created the new release. Thank you. :)

**Comment by jbkuma** [comment]
My only issue with this fix is I don't always want it to be advertising just because it is disconnected.  I may want it disconnected, such as I shut my PC down for the evening, and I don't want my neighbors randomly connecting to it.  I prefer rousir's build with which I can remain connected with an isConnected check and retrigger advertising with a startAdvertising, or manual trigger advertising when I want to reconnect

**Comment by T-vK** [comment]
The problem with rousir's build is that it would break backwards-compatibility. Maybe we can add an option to disable automatic advertising.

**Comment by markingle** [comment]
I think a switch in the startAdvertising function would do the trick.

**Pull request merged**
