### PR TITLE
Fix for #115

### LINKED ISSUE #115: Keyboard stops working after reconnect
Hi, I am using the  0.3.0 version with Windows 10 and I noticed, that when I add after I add the esp32 keyboard as a new bluetooth device on my windows computer, everything works just fine, the keys work and all, but if the bluetooth conenction is lost, because i turn the esp32 off and on for example, then even though the windows reconnects to the esp32 and it changes status from PAIRED to CONNECTED under the bluetooth devices, the keyboard no longer works and the only way to make it work again is to remove the esp32 keyboard from bluetooth devices on windows and then add it again, after which it works until the next time signal is lost.

I tried downgrading to 0.2.3 which works flawlessly and doesn't have this bug.

### PR DESCRIPTION
**Pull request by sivar2311**
This fixes #115

### CODE REVIEW

**Comment by T-vK** [comment]
Sorry for letting you wait for so long. I'm currently thinking about creating some sort of beta branch that I can use to accept PRs faster and then also create beta releases for those PRs. This way we can have new (beta) releases without testing them on all platforms. And those beta releases can then be turned into a stable release once they have been tested for all platforms.

**Comment by sivar2311** [comment]
Apology accepted ;)

The idea sounds good. 
What would the workflow look like? 
Do I have to create a new branch in a fork?

**Comment by T-vK** [comment]
I'm not sure yet. My initial idea was that I simply add a branch called beta and then you could merge your branch into that beta branch via PR. But maybe it would be a better idea to simply say that the master by itself is not stable and if you want a stable version of the source code, you have to checkout a release tag.

**Comment by sivar2311** [comment]
> But maybe it would be a better idea to simply say that the master by itself is not stable and if you want a stable version of the source code, you have to checkout a release tag.

I think that's the usual way. The master is the "development environment" and stable versions are tagged. Afaik both the ArduinoIDE Library Manager and PlatformIO use the release labels.

**Comment by T-vK** [comment]
Okay let's do it that way then. I've merged the PR and created a beta tag and a beta release for it now.

You seem to be quite interested in this project. I would like to add you as a collaborator, so you don't have to create PRs all the time and wait for me. What do you think?

**Comment by sivar2311** [comment]
Thank you for the offer. It sounds interesting. I'm in. :)

I would also be interested in direct contact (WhatsApp / Telegram) - What do you think?

**Comment by sivar2311** [comment]
BTW: I'm still trying to figure out the HID stuff. I would also be very interested in sending special characters. I am from Germany and I am missing the "Umlaute" (äöüß).

**Comment by T-vK** [comment]
I'm not comfortable sharing my phone number, but you can hit me up on t-vk.dev@gmx.net if you want.
Regarding keyboard layouts, I'm not sure how we should solve this yet. It's important to me to not break compatibility with the [Arduino keyboard library](https://github.com/arduino-libraries/Keyboard), so the default will have to stay the US layout.
It would probably make sense to save every keyboard layout in its own header file and let the user pick one by specifying it using something like `#define KEYBOARD_LAYOUT us`.

At the moment the layout is hardcoded here: 
https://github.com/T-vK/ESP32-BLE-Keyboard/blob/4d93a0497dd307f237a83bcf69aa1ae21f496bcc/BleKeyboard.cpp#L215-L349
and potentially also here: 
https://github.com/T-vK/ESP32-BLE-Keyboard/blob/4d93a0497dd307f237a83bcf69aa1ae21f496bcc/BleKeyboard.h#L29-L76

(I'm not sure if those keys actually differ in different layouts though.)

**Comment by sivar2311** [comment]
Yes, I know those lines.

I am still not quite clear about the conversion of ascii codes to HID codes.

My idea would be to work with a std::vector instead of a static array. Alternatively, we could use a pointer to an array internally (which points to the fixed ascii table by default), but which can be changed to a custom table by the user.

**Comment by T-vK** [comment]
I think the name of the variable `_asciimap` (which I just copied from the USB Keyboard library) is a bit misleading because it contains keyboard scan codes and not a classic ascii table. We basically just need a different mapping for each keyboard layout. I'm not sure what would be the best way of doing it, but I would vote for a way that only compiles the wanted keyboard layout so that we don't end up with memory issues again in the future. 
You probably know better than me if std:vector, an array or a pointer would be the best way to achieve this.

**Comment by sivar2311** [comment]
The name is suitable. The array maps the Ascii code to the corresponding scan code.
I have two problems to understand this.
First, I don't know the meaning of the scan codes. For example, what is the scan code for "ö"?
Second, in the `press` function the _ascii map is limited to 128: `} else if (k >= 128) { // it's a modifier key`

So ascii codes > 128 are not possible at all. But exactly there are the umlauts and characters of other languages.

**Comment by sivar2311** [comment]
Ok, i think begin to get a feeling for this.
To get `xyzäöü` i need to send `xzy';[` (US-Layout)

**Comment by sivar2311** [comment]
Thank's for the images!

I am thinking about using a std::map instead of a fixed array.
This map can be initialized with standard us-codes and modified later.
[Here](https://gist.github.com/sivar2311/36aca08f296289b3f7aebe1ef151fe35) you can see what i mean - fist (and very basic) approach.
Looks like this topic is much more complicated because it is related to ASCII codes, code pages and HID key codes

**Comment by sivar2311** [comment]
I think i've found a solution - check the new branch [Layout](https://github.com/sivar2311/ESP32-BLE-Keyboard/blob/Layout/examples/GermanKeyboard/GermanKeybord.ino) (still in my repository)

`_asciimap` is now a member of BleKeyboard and of type `KbdLayout` which is a `std::map<uint8_t, uint8_t>`
The map takes the ascii code as first parameter and the hid key-code as second parameter and is initialized with the US layout. 
The function `modifyKbdLayout` has been implemented to alter the keyboard mapping - see [GermanKeyboard.ino](https://github.com/sivar2311/ESP32-BLE-Keyboard/blob/Layout/examples/GermanKeyboard/GermanKeyboard.ino) example
The functions `press` and `release` have been changed to accept ascii codes > 127

**Comment by T-vK** [comment]
Nice, I like it. Maybe it can be improved further in a way that the user doesn't have to worry about the layout code. Something like this maybe:

```|
#include "Layouts/German.h"

bleKeyboard.setLayout(DE_LAYOUT);
````

**Comment by sivar2311** [comment]
Sure, this can be outsourced to individual header files.
The most difficult thing will be to define the layouts.

**Comment by T-vK** [comment]
I think so far no one has asked me for layouts other than DE and FR. So that would probably already be pretty valueable for the community. Other layouts ciuld be added in the future. I don't think it would be necessary to add all layouts now.

**Pull request merged**
