### PR TITLE
NimBLE-Arduino (optional) and remove of xTaskCreate

### PR DESCRIPTION
**Pull request by sivar2311**
# NimBLE-Mode
This implements NimBLE-Mode to reduce memory consumption 
ArduinoIDE: Before including the library, insert the line `#define USE_NIMBLE`
```C++
#define USE_NIMBLE
#include <BleKeyboard.h>
```

PlatformIO: Change your `platformio.ini` to the following settings
```ini
lib_deps = 
  NimBLE-Arduino

build-flags = 
  -D USE_NIMBLE
```

## Comparison (SendKeyStrokes.ino at run-time)

|   | Standard | NimBLE mode | difference
|---|--:|--:|--:|
| `ESP.getHeapSize()`   | 296.804 | 321.252 | **+ 24.448**  |
| `ESP.getFreeHeap()`   | 143.572 | 260.764 | **+ 117.192** |
| `ESP.getSketchSize()` | 994.224 | 579.264 | **- 414.960** |

# `xTaskCreate`
xTaskCreate was removed to fix stack issues.

### CODE REVIEW

**Comment by sivar2311** [comment]
> But technically spekaing vTaskDelay is probably doing way more than setting the delay between key events, so I'm not sure.

I have used vTaskDelay only because the arduino `delay` is not available (Arduino.h is not included). 
If you have a better idea, let me know :)

> I think in addition to adding that function, we should also make the the default high enough to make it work on "most" devices.

I agree. We just have to find out how high this value has to be.
On my Windows system, a value of 1 was already enough. 
This was not enough on my Samsung Galaxy (but I have not yet determined an exact value here). 

> I'd be okay with setKeyDelay

Perfect :)

**Comment by sivar2311** [comment]
I have changed my mind. `setDelay` is a more neutral name ;)
For this I implemented a simple `delay_ms` function. 
At the moment this is only used in NimBLE mode.

My tests have shown the following settings for a stable transmission:
Windows 2 ms
Android 7 ms

For this reason I have taken a default value of 7 ms.

However, this may be different on different PCs / Android phones.

**Comment by T-vK** [comment]
Great, let's go with 7 as a default then. If this doesn't work for everyone, I'll find out eventually and increase it.

**Comment by sivar2311** [comment]
3 milliseconds on my son's iPhone 8.

**Comment by T-vK** [comment]
Can you add this line to the library.properties file?

```
depends=NimBLE-Arduino
```

**Comment by sivar2311** [comment]
> Can you add this line to the library.properties file?
`depends=NimBLE-Arduino`

I am not sure if this is a good idea as NimBLE-Arduino is optional.
I also had the idea to create a `library.json` for PlatformIO and to add the NimBLE-Arduino in the dependencies section. But I haven't done it yet for the same reason.

> The only issue I noticed is that when I turn Bluetooth off on Linux without manually disconnecting first, the disconnect even never gets fired resulting in isConnected() to keep returning true.

This looks like a Linux problem to me. 
On Windows and Android the  `onDisconnect` callback is triggered properly as soon as Bluetooth is turned off on the client side.

**Comment by T-vK** [comment]
> I am not sure if this is a good idea as NimBLE-Arduino is optional.
> I also had the idea to create a `library.json` for PlatformIO and to add the NimBLE-Arduino in the dependencies section. But I haven't done it yet for the same reason.
I agree, I'm not sure either. I guess we leave it as is for now. But it might make sense to make NimBLE the default at some point. 

> This looks like a Linux problem to me.
I don't know, I feel like Windows and Android are probably sending a disconnect signal to the ESP before turning off. If the Windows machine crashed or  lost power while being connected you'd probably end up in the same state. So while it would probably seemingly fix the problem if Linux were to send that disconnect signal, I feel like the ESP should be capable of recovering from an unannounced disconnect. But I don't think this issue has anything to do with your PR.

**Comment by sivar2311** [comment]
I don't know how Windows would behave in the event of a crash (the last time was several years ago). 
But the original problem was switching off the Bluetooth - so it's a different situation.

I don't know how to determine whether a BLE connection still exists. 
Then a polling or something similar would have to take place regularly. 
That will hardly be possible with BLE, or it would be counterproductive with regard to the "low energy" concept.

The problem is probably that the client does not disconnect the connection cleanly. But you can't blame the host for that ;)

I don't know enough details about how BLE works on the ESP. I am only a user of the (Nim)BLE library.

**Comment by T-vK** [comment]
I will find a way to address that issue eventually, I mean other BLE devices manage to do it too, but it's a low priority at the moment.  :)

**Comment by sivar2311** [comment]
Yes, I think so too.
One step at a time... :)

**Comment by tahunus** [comment]
Thanks!  Works as you mentioned!

**Pull request merged**
